### ISSUE TITLE
X/Y axis labels wrong on os-x

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/Pixelpulse2#163]
in the X/Y plots - the labels were being shown as 0.00000000001 - which consumed all the screen space. Only happens on OS-X.

-Robin

While updating that code - Also noticed that axises don't use the same number of digits (which they should).

For example:

![image](https://cloud.githubusercontent.com/assets/1017869/13993287/1cbb6314-f0f6-11e5-8ead-f23c608e4c1a.png)

should be 0.20, 0.15, 0.10, 0.05, 0.00, etc

**Comment by luciansin** [comment]
Same number of digits fixed in Windows.
It was tested with v0.89 and on Win7.32bits, Win7.64bits, Win10.32bits and Win10.64bits.

**Comment by rgetz** [comment]
The original issue reported was X/y plots on OS-X. 

Does that still occur?

**Comment by luciansin** [comment]
X/Y plots on OS-X work now. Bug fixed and closed.

**Comment by rgetz** [comment]
It wasn't that they didn't work, it was that the printed out too many decimal places. 0.1 was "0.1000000001"

**Comment by luciansin** [comment]
Now the maximum number of decimals is 4.
